import Head from "next/head"
import DashboardShell from "../../components/DashboardShell"
import { Title, Paper, ThemeIcon, Group, Card, Text, useMantineTheme, Button, Box } from "@mantine/core"
import { IoCheckmarkCircleOutline } from 'react-icons/io5'
import { dashboardItems } from "../../lib/navItems"
import Link from "next/link"
import { IoArrowForward } from 'react-icons/io5'


const ImportSuccess = () => {

    const theme = useMantineTheme();

    const secondaryColor = theme.colorScheme === 'dark'
        ? theme.colors.dark[1]
        : theme.colors.gray[7];

        const cardSection = {
            display: 'grid',
            gridTemplateColumns: '1fr 1fr',
            gap: '2rem',
            paddingTop: '2rem',
            maxWidth: '900px',
            '& h2': {
              fontSize: '1.3rem',
              fontWeight: 700,
              paddingBottom: '.5rem',
              color: '#002237'
            },
            '& p': {
              color: '#647795'
            },
            '& svg': {
              height: '18px',
              width: '18px',
              marginRight: '.5rem',
            },
            '@media (max-width: 900px)': {
              gridTemplateColumns: '1fr',
              gap: '1rem'
            }
          }

    return (
        <>
            <Head>
            <title>Shake Metrics</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <DashboardShell>
                    <Title color='dimmed' size='xl' weight={700} mb='xl'>
                        Success
                    </Title>
                    <Text color='dimmed'>Right on! Your data has been successfuly imported. What do you want to see first?</Text>
                    <Box sx={cardSection}>
                        {
                            dashboardItems.map( item => (
                                <Card 
                                    key={item.id} 
                                    shadow="lg"
                                    radius='md' 
                                    padding="lg"
                                    withBorder
                                >
                                    <Text 
                                        weight={700}
                                        size='xl'
                                    >
                                        {item.title}
                                    </Text>
                                    <Box sx={{minHeight: '50px'}}>
                                        <Text 
                                        size="sm" 
                                        style={{ 
                                            color: secondaryColor, 
                                            lineHeight: 1.5, 
                                        }}
                                        >
                                            {item.description}
                                        </Text>
                                    </Box>
                                    <Link href={item.path} passHref>
                                        <Button 
                                            variant="outline" 
                                            color="blue" 
                                            fullWidth
                                            size='sm' 
                                            style={{ marginTop: 14 }}
                                            rightIcon={<IoArrowForward />}
                                        >
                                            Go to {item.title}
                                        </Button>
                                    </Link>
                                </Card>
                            ))
                        }
                    </Box>

            </DashboardShell>
        </>
    )
}

export default ImportSuccess