import Head from "next/head"
import DashboardShell from "../../components/DashboardShell"
import { Title, Text, } from "@mantine/core"
import DashboardCards from "../../components/DashboardCards"


const ImportSuccess = () => {

    return (
        <>
            <Head>
            <title>Shake Metrics</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <DashboardShell>
                <Title color='dimmed' size='xl' weight={700} mb='xl'>
                    Success
                </Title>
                <Text color='dimmed'>
                    Right on! Your data has been successfuly imported. What do you want to see first?
                </Text>
                <DashboardCards left={true} />

            </DashboardShell>
        </>
    )
}

export default ImportSuccess