import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import usePrices from '../hooks/usePrices'
import DashboardShell from '../components/DashboardShell'

export default function Home() {

  console.log(usePrices())

  return (
    <div>
      <Head>
        <title>Shake Metrics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DashboardShell>
        Current bitcoin price: {usePrices().marketData.price.BTC}
      </DashboardShell>

    </div>
  )
}
