import Head from 'next/head'
import DashboardShell from '../components/DashboardShell'
import { Text, Box, Button, Group, useMantineTheme } from '@mantine/core'
import DashboardCards from '../components/DashboardCards'
import Link from 'next/link'

export default function Home() {

  const theme = useMantineTheme();

  const secondaryColor = theme.colorScheme === 'dark'
      ? theme.colors.dark[1]
      : theme.colors.gray[7];

  const headlineStyle = (theme) => ({
    fontSize: '3.5rem',
    [`@media (max-width: ${theme.breakpoints.sm}px)`]: {
      fontSize: '2.5rem',
    }
  })


  return (
    <div>
      <Head>
        <title>Shake Metrics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DashboardShell noNav={true}>
        <h2>Coming soon...</h2>
        {/* <Group direction='column' position='center' sx={{textAlign: 'center'}} spacing={0}>
          <Text>Free Shakepay Extension</Text>
          <Text 
            sx={headlineStyle} 
            weight={700}
          >
            Skip the Spreadsheets.
          </Text>
          <Box sx={{maxWidth: '750px'}}>
            <Text
              size='lg'
              mt='xs'
              mb='md'
              weight={500}
              sx={(theme) => ({
                color: secondaryColor,
                '& span': {
                  fontWeight: 700,
                },
                '& .highlight': {
                  color: theme.colors.blue[4]
                }
              })}
            >
              Instantly see how your <span className='highlight'>Shakepay</span> portfolio is performing, stats from <span>#shakingsats</span> and using your <span>#cashbackcard</span>, tax details and more, without having to spend your time digging through and trying to make sense of your raw CSV file
            </Text>
          </Box>
          <Group spacing='sm' mt='md' mb='md'>
            <Link href='/import' passHref>
              <Button
                size='md'
              >
                See Your Report
              </Button>
            </Link>
            <Link href='/dashboard/performance' passHref>
              <Button 
                variant='outline'
                size='md'
              >
                See Live Demo
              </Button>
            </Link>
          </Group>
          <Box sx={{maxWidth: '750px'}}>
            <DashboardCards sx={{gridTemplateColumns: '1fr 1fr'}}/>
          </Box>
        </Group> */}
      </DashboardShell>

    </div>
  )
}
